MOUSEKEY_ENABLE = yes    # Mouse keys
RGBLIGHT_ENABLE = no    # Enable WS2812 RGB underlight.
CONSOLE_ENABLE  = no         # Console for debug
COMMAND_ENABLE  = no         # Commands for debug and configuration
OLED_ENABLE     = yes
OLED_DRIVER     = SSD1306
LTO_ENABLE      = yes
LEADER_ENABLE   = yes
SRC            += caps_word.c
